Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -94,7 +94,9 @@ jobs:
             echo "Starting application..."
             sudo /usr/bin/docker compose up --build -d
 
-      - name: 'Update DuckDNS with new IP'
+      - name: Update DuckDNS with new IP
         run: |
-          echo "Updating DuckDNS record for ${{ secrets.DUCKDNS_DOMAIN }}..."
-          echo url="https://www.duckdns.org/update?domains=${{ secrets.DUCKDNS_DOMAIN }}&token=${{ secrets.DUCKDNS_TOKEN }}&ip=${{ needs.terraform.outputs.public_ip }}" | curl -k -K -
+         response=$(curl -fsSL \
+         "https://www.duckdns.org/update?domains=${{ secrets.DUCKDNS_DOMAIN }}&token=${{ secrets.DUCKDNS_TOKEN }}&ip=${{ needs.terraform.outputs.public_ip }}")
+         echo "DuckDNS update response: $response"
+         [[ "$response" == "OK" ]] || (echo "DuckDNS update failed" && exit 1)
